name: PhroLova Kernel

on:
  workflow_dispatch:
  watch:
    types: [started]

defaults:
  run:
    shell: bash

jobs:
  buildtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [KSU, NonKSU]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Install Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            dialog bash sed wget git curl zip tar jq expect make cmake automake autoconf \
            llvm lld lldb clang gcc binutils bison perl gperf gawk flex bc python3 python3-pip zstd \
            openssl unzip cpio build-essential ccache liblz4-tool libsdl1.2-dev libstdc++6 \
            libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev \
            libncurses5-dev bzip2 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf \
            gcc-arm-linux-gnueabi dos2unix kmod
          
          # Install Telethon untuk Userbot
          python3 -m pip install telethon

      - name: Setup WeebX Clang
        run: |
          mkdir -p weebx-clang
          cd weebx-clang
            wget -q $(curl -k https://raw.githubusercontent.com/XSans0/WeebX-Clang/main/main/link.txt) -O weebx-clang.tar.gz
            tar -xf weebx-clang.tar.gz
            rm -f weebx-clang.tar.gz

      - name: Fetch KernelSU-SuSFS
        run: |
          # curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy
          curl -LSs "curl -LSs "https://raw.githubusercontent.com/MDonip/KernelSU-Next/legacy-susfs-4.9/kernel/setup.sh" | bash -s legacy-susfs-4.9 
      - name: Start Build with log
        env:
          KBUILD_BUILD_USER: "localhost"
          KBUILD_BUILD_HOST: "admin"
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
          TELE_API_ID: ${{ secrets.TELE_API_ID }}
          TELE_API_HASH: ${{ secrets.TELE_API_HASH }}
          TELE_SESSION: ${{ secrets.TELE_SESSION }}
        run: |
          mkdir -p logs
          bash yoru.sh ${{ matrix.variant }} 2>&1 | tee logs/build-${{ matrix.variant }}.txt

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log-${{ matrix.variant }}
          path: logs/build-${{ matrix.variant }}.txt

      - name: Upload AnyKernel Zip
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: anykernel-zip-${{ matrix.variant }}
          path: AnyKernel/*.zip

      - name: Upload Kernel Image
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: image-gz-${{ matrix.variant }}
          path: out/arch/arm64/boot/Image.gz

      - name: Upload DTB
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: image-gz-dtb-${{ matrix.variant }}
          path: out/arch/arm64/boot/Image.gz-dtb
          
